### PR TITLE
Disabled Soldering station recipes

### PR DESCRIPTION
**Pull request by Ethryan**
Untested but it should just hide the unused soldering station from NEI

BTW, please put 0.9.3-mc1.7.10 as main branch.

### CODE REVIEW

**Comment by Dream-Master** [comment]
> Untested but it should just hide the unused soldering station from NEI
> 
> BTW, please put 0.9.3-mc1.7.10 as main branch.

change 0.9.3 to default one

**Comment by Ethryan** [comment]
I will test this change when i get home before doing a new version and merging

**Comment by Dream-Master** [comment]
why the soldering station disabled ?

**Comment by Ethryan** [comment]
1. It don't use GT Power
2. It can't accept fluids
3. Recipes has to be hardcoded inside the mod.
4. Don't match any GT Machine
image
5. I would rather use the Assembler and Circuit assembler for LP recipes.

**Comment by Ethryan** [comment]
This pull works from my testing.

**Comment by Dream-Master** [comment]
ok

**Pull request merged**
